# Generated by Django 3.2.5 on 2021-08-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrecentCHECKD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Python_p', models.IntegerField()),
                ('CyberSecruity_p', models.IntegerField()),
                ('Web_p', models.IntegerField()),
                ('Andriod_p', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=50)),
                ('Desprecent', models.TextField()),
                ('url', models.CharField(max_length=50)),
                ('Date_started', models.CharField(max_length=10)),
                ('website_uploaded_project', models.CharField(max_length=10)),
            ],
        ),
    ]
